// Generated by gencpp from file cw2_world_spawner/Task3Service.msg
// DO NOT EDIT!


#ifndef CW2_WORLD_SPAWNER_MESSAGE_TASK3SERVICE_H
#define CW2_WORLD_SPAWNER_MESSAGE_TASK3SERVICE_H

#include <ros/service_traits.h>


#include <cw2_world_spawner/Task3ServiceRequest.h>
#include <cw2_world_spawner/Task3ServiceResponse.h>


namespace cw2_world_spawner
{

struct Task3Service
{

typedef Task3ServiceRequest Request;
typedef Task3ServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Task3Service
} // namespace cw2_world_spawner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cw2_world_spawner::Task3Service > {
  static const char* value()
  {
    return "a4cdcbf342ebe5d2a91b198b8ea6a615";
  }

  static const char* value(const ::cw2_world_spawner::Task3Service&) { return value(); }
};

template<>
struct DataType< ::cw2_world_spawner::Task3Service > {
  static const char* value()
  {
    return "cw2_world_spawner/Task3Service";
  }

  static const char* value(const ::cw2_world_spawner::Task3Service&) { return value(); }
};


// service_traits::MD5Sum< ::cw2_world_spawner::Task3ServiceRequest> should match
// service_traits::MD5Sum< ::cw2_world_spawner::Task3Service >
template<>
struct MD5Sum< ::cw2_world_spawner::Task3ServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cw2_world_spawner::Task3Service >::value();
  }
  static const char* value(const ::cw2_world_spawner::Task3ServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cw2_world_spawner::Task3ServiceRequest> should match
// service_traits::DataType< ::cw2_world_spawner::Task3Service >
template<>
struct DataType< ::cw2_world_spawner::Task3ServiceRequest>
{
  static const char* value()
  {
    return DataType< ::cw2_world_spawner::Task3Service >::value();
  }
  static const char* value(const ::cw2_world_spawner::Task3ServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cw2_world_spawner::Task3ServiceResponse> should match
// service_traits::MD5Sum< ::cw2_world_spawner::Task3Service >
template<>
struct MD5Sum< ::cw2_world_spawner::Task3ServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cw2_world_spawner::Task3Service >::value();
  }
  static const char* value(const ::cw2_world_spawner::Task3ServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cw2_world_spawner::Task3ServiceResponse> should match
// service_traits::DataType< ::cw2_world_spawner::Task3Service >
template<>
struct DataType< ::cw2_world_spawner::Task3ServiceResponse>
{
  static const char* value()
  {
    return DataType< ::cw2_world_spawner::Task3Service >::value();
  }
  static const char* value(const ::cw2_world_spawner::Task3ServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CW2_WORLD_SPAWNER_MESSAGE_TASK3SERVICE_H
