// Generated by gencpp from file cw2_world_spawner/Task2Service.msg
// DO NOT EDIT!


#ifndef CW2_WORLD_SPAWNER_MESSAGE_TASK2SERVICE_H
#define CW2_WORLD_SPAWNER_MESSAGE_TASK2SERVICE_H

#include <ros/service_traits.h>


#include <cw2_world_spawner/Task2ServiceRequest.h>
#include <cw2_world_spawner/Task2ServiceResponse.h>


namespace cw2_world_spawner
{

struct Task2Service
{

typedef Task2ServiceRequest Request;
typedef Task2ServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Task2Service
} // namespace cw2_world_spawner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cw2_world_spawner::Task2Service > {
  static const char* value()
  {
    return "48fa6a1a8f22948fb54540fdb831dc23";
  }

  static const char* value(const ::cw2_world_spawner::Task2Service&) { return value(); }
};

template<>
struct DataType< ::cw2_world_spawner::Task2Service > {
  static const char* value()
  {
    return "cw2_world_spawner/Task2Service";
  }

  static const char* value(const ::cw2_world_spawner::Task2Service&) { return value(); }
};


// service_traits::MD5Sum< ::cw2_world_spawner::Task2ServiceRequest> should match
// service_traits::MD5Sum< ::cw2_world_spawner::Task2Service >
template<>
struct MD5Sum< ::cw2_world_spawner::Task2ServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cw2_world_spawner::Task2Service >::value();
  }
  static const char* value(const ::cw2_world_spawner::Task2ServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cw2_world_spawner::Task2ServiceRequest> should match
// service_traits::DataType< ::cw2_world_spawner::Task2Service >
template<>
struct DataType< ::cw2_world_spawner::Task2ServiceRequest>
{
  static const char* value()
  {
    return DataType< ::cw2_world_spawner::Task2Service >::value();
  }
  static const char* value(const ::cw2_world_spawner::Task2ServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cw2_world_spawner::Task2ServiceResponse> should match
// service_traits::MD5Sum< ::cw2_world_spawner::Task2Service >
template<>
struct MD5Sum< ::cw2_world_spawner::Task2ServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cw2_world_spawner::Task2Service >::value();
  }
  static const char* value(const ::cw2_world_spawner::Task2ServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cw2_world_spawner::Task2ServiceResponse> should match
// service_traits::DataType< ::cw2_world_spawner::Task2Service >
template<>
struct DataType< ::cw2_world_spawner::Task2ServiceResponse>
{
  static const char* value()
  {
    return DataType< ::cw2_world_spawner::Task2Service >::value();
  }
  static const char* value(const ::cw2_world_spawner::Task2ServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CW2_WORLD_SPAWNER_MESSAGE_TASK2SERVICE_H
